const projects = [
    {
        "group": 601,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Ampre",
        "population": "Personas con discapacidad",
        "title": "Maiasa - Ampre: Sociabilización inclusiva y desarrollo humanitario",
        "objective": "Proporcionar los integrantes de nuestra comunidad: talleres, herramientas, conocimientos y mentoría.",
        "description": "1. Participar en el curso de Liderazgo\n2. Realizar assessments de autoevaluación\n3. Trabajar un proyecto en equipo\n4. Participar en las actividades sabatinas dentro de nuestra institución",
        "schedule": "Sábados 10:30 a 13:30",
        "tags": "Todas",
        "abilities": "Creatividad, Liderazgo, Empatía, Pensamiento Incluyente, Actitud Positiva y Compromiso.",
        "max": 150,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Ahuacan 8, Cantera Puente de Piedra, Tlalpan, 14040 Ciudad de México, CDMX",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 1,
        "image": "/ampre.webp"
    },
    {
        "group": 602,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Ampre",
        "population": "Todo tipo de minorías",
        "title": "Maiasa: Creando una app de conocimiento humanitario",
        "objective": "Avanzar en el desarrollo de la app Maiasa",
        "description": "1. Guiones de videos de TikTok de sociología, filosofía, psicología u otros estudios humanitarios.\n2. Diseño o programación de una app de aprendizaje.\n3. Apoyar en la creación de eventos para ODS y ONGs",
        "schedule": "Por Acordar",
        "tags": "LAD, LDI, LEC, LC, LEI, LPE, IDS, IRS, ITC, ITD, IID, IMT, LPS, LAE, LDE, LEM",
        "abilities": "Programación, diseño, conocimiento humanitario (psicología, sociología, filosofía, etc,), Investigación o desarrollo de guiones.",
        "max": 50,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Ampre",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 2,
        "image": "/ampre.webp"
    },
    {
        "group": 645,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Asociación Exatec STEAM",
        "population": "Niñ@s (8+), adolescentes, padres de familia, profesores e interesados en áreas STEAM",
        "title": "Soporte a la Asociación Exatec STEAM para la difusión y sensibilización de habilidades STEAM.",
        "objective": "Dar soporte al los diversos programas de la Asociación",
        "description": "1. Apoyo para la organización de eventos\n2. Apoyo para la generación de contenido STEAM\n3. Apoyo al desarrollo de programas que trae la asociación para filantropía, reducción de brecha de género, etc.",
        "schedule": "Por acordar",
        "tags": "Todas",
        "abilities": "Trabajo en equipo, proactivo, asertivo, enfocado, creativo y con ganas de apoyar ",
        "max": 15,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "En línea o presencial, dependiendo de la actividad.",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 3,
        "image": "/tec-logo.webp"
    },
    {
        "group": 646,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Asociación Exatec STEAM",
        "population": "Niños, niñas, adolescentes padres de familia, docentes desde 8 años en adelante.",
        "title": "Soporte a la Asociación EXATEC STEAM para desarrollo de Contenidos de las Redes Sociales",
        "objective": "Desarrollo de contenidos para RRSS, en temas STEAM atractivo para cada tipo de público objetivo.",
        "description": "1. Revisión (estrategia, diseños propuestos, avances técnicos,-) \n2. Pag WEB y redes sociales operando\n3. Estrategia y desarrollo de motor de contenidos\n5. Mantenimiento\n5. Generación de contenidos.",
        "schedule": "Lunes de 18:00 a 19:00 hrs",
        "tags": "Todas",
        "abilities": "Trabajo en equipo, proactivo, asertivo, enfocado a resultados, con ganas de apoyar. ",
        "max": 10,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Campus CCM y Virtual",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 4,
        "image": "/tec-logo.webp"
    },
    {
        "group": 603,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Asociación Mexicana de la Enfermedad de Huntington I.A.P.",
        "population": "Toda persona que padezca la enfermedad de Huntington en situación vulnerable de la República mexicana sin importar sexo, edad, preferencias sexuales ni religión.",
        "title": "Crear medios de difusión para dar a conocer la Organización.",
        "objective": "Que el alumno use su creatividad para elaborar contenidos de impacto.",
        "description": "1. Investigar sobre  la E.H. y labor de la Asociación.\n2. Con base a la información elaborar post, historietas y videos atractivos y concisos para atrapar la atención de los usuarios de redes sociales.",
        "schedule": "Lunes a jueves de 9:00 a 18:00 y viernes de 9:00 a 14:00 hrs, domingo 10 de noviembre de 9:30 a 12:00 hrs",
        "tags": "LAD, LED, LC, LPE, LTM",
        "abilities": "Manejo de redes sociales, manejo de aplicación de edición de video, Creatividad, Responsabilidad, compromiso, trabajo en equipo.",
        "max": 6,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Cuauhtémoc 97, Col. Toriello Guerra Tlalpan CDMX ",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 5,
        "image": "/huntington.webp"
    },
    {
        "group": 604,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Asociación mexicana de la enfermedad de Huntington I.A.P.",
        "population": "Toda persona que padezca la enfermedad de Huntington en situación vulnerable de la República mexicana sin importar sexo, edad, preferencias sexuales ni religión.",
        "title": "Apóyanos en el área administrativa y contable.",
        "objective": "Fortalecimiento organizacional mediante la sistematización administrativa y contable.",
        "description": "Actualización de control de inventarios, bases de datos y estadísticas, manuales de la organización.",
        "schedule": "lunes a jueves de 9:00 a 18:00 viernes 9:00 a 14:00 domingo 10 de noviembre de 9:30 a 12:00 hrs",
        "tags": "LBC, LAE, LAF, LCPF, LEM",
        "abilities": "Responsabilidad, Creatividad, compromiso, trabajo en equipo.",
        "max": 6,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Cuauhtémoc 97 Col. Toriello Guerra, Tlalpan CDMX",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 6,
        "image": "/huntington.webp"
    },
    {
        "group": 605,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Asociación para Leer escuchar Escribir y Recrear A. C. (iBbY México).",
        "population": "Infancia y adolescencia neurotípica y también con alguna condición particular de vida como: Discapacidad, migración, acceso al bienestar, etc.",
        "title": "Libros al viento: Mixcoac y Roma-Condesa",
        "objective": "Favorecer experiencias de lectura significativa para diferentes groups de edad.",
        "description": "1.- Reunión de inicio.\n2.- Reunión de inducción con la comunidad.\n3.- Desarrollo de actividades de fomento a la lectura con comunidad.",
        "schedule": "Lunes a domingo de 10:00 a 18:00 horas",
        "tags": "Todas",
        "abilities": "Compromiso, responsabilidad, empatía, trabajo en equipo, solidaridad.",
        "max": 15,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Direcciones:  Biblioteca BS iBbY México: Horario: Lunes a domingo  de 10 a 18 horas Goya 54, Col. Insurgentes Mixcoac, Benito Juárez, 03920 Ciudad de México, CDMX Bunko Roma-Condesa: Horario: Miércoles a domingo de 10-18 horas Orizaba 37, Col. Roma Norte, Cuauhtémoc, 06700 Ciudad de México, CDMX",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 7,
        "image": "/ibby.webp"
    },
    {
        "group": 606,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Asociación para Leer escuchar Escribir y Recrear A. C. (iBbY México).",
        "population": "Infancia y adolescencia neurotípica y también con alguna condición particular de vida como: Discapacidad, migración, acceso al bienestar, etc.",
        "title": "Libros al viento: Xochimilco",
        "objective": "Favorecer experiencias de lectura significativa para diferentes groups de edad.",
        "description": "1.- Reunión de inicio.\n2.- Reunión de inducción con la comunidad.\n3.- Desarrollo de actividades de fomento a la lectura con comunidad.",
        "schedule": "Lunes a viernes de 10:00 a 18:00 horas",
        "tags": "Todas",
        "abilities": "Compromiso, responsabilidad, empatía, trabajo en equipo, solidaridad.",
        "max": 10,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Bunko Xochimilco: Horario: martes a sábado de 11 a 19 horas Gustavo Díaz Ordaz 35, San Gregorio Atlapulco, Xochimilco; 16630 Ciudad de México, CDMX Mapas: https://goo.gl/maps/DfSEjahJXTs2ESGXA",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 8,
        "image": "/ibby.webp"
    },
    {
        "group": 607,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Bienestar Estudiantil",
        "population": "Estudiantes universitarios de ambos sexos, entre los 18 y 24 años de edad en promedio. ",
        "title": "Bienestar Estudiantil, conecta.",
        "objective": "Acercar  herramientas de bienestar mental integral, así como la prevención de conductas de riesgo.",
        "description": "1. Elaborar materiales audiovisuales para las distintas actividades, proyectos y campañas del departamento. \n2. Generar que más estudiantes se agreguen a la comunidad desde las redes sociales.",
        "schedule": "lunes a viernes de 8:00 a 19:00 (horario flexible)",
        "tags": "ARQ, LAD, LDI, LC",
        "abilities": "Uso de herramientas de construcción audiovisual. Photoshop- Ilustrator, Canvas, etc. Comunicación efectiva, asertiva y direccionada.",
        "max": 6,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Campus CCM",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 9,
        "image": "/bienestar-estudiantil.webp"
    },
    {
        "group": 608,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Biointellectus",
        "population": "Biointellectus atiende una población que no esta diferenciada por edad o genero, ya que ofrecemos una solución a toda persona que busca tener una vida con menos impacto ambiental.",
        "title": "DeerPlanet - un videojuego para aprender de bioplásticos",
        "objective": "Impactar a la educación ambiental a través de la gamificación.",
        "description": "1. Trabajar en el desarrollo de la mecánica del juego .\n2. Realizar pruebas de funcionalidad. \n3.  integrar los trabajos previos .",
        "schedule": "Por acordar con OSF",
        "tags": "ITC",
        "abilities": "Indispensable experiencia con C++, experiencia trabajando con Unity.",
        "max": 10,
        "model": "CLIN | Proyecto Solidario en Línea",
        "location": "Online",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 10,
        "image": "/biointellectus.webp"
    },
    {
        "group": 609,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Biointellectus ",
        "population": "Biointellectus atiende una población que no esta diferenciada por edad o genero, ya que ofrecemos una solución a toda persona que busca tener una vida con menos impacto ambiental.",
        "title": "Construcción y optimización de sitio web ",
        "objective": "El objetivo deseado es la construcción del back y front de un sitio web dedicada a la educación.\n",
        "description": "Participar en las actividades de codificación para la construcción del back & front de la página web",
        "schedule": "Por acordar con OSF",
        "tags": "ITC",
        "abilities": "Para ITCs es indispensable tener conocimiento de desarrollo web pues se incorporaran a un proyecto previamente iniciado de carácter profesional.",
        "max": 8,
        "model": "CLIN | Proyecto Solidario en Línea",
        "location": "Online",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 11,
        "image": "/biointellectus.webp"
    },
    {
        "group": 610,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Bufetec/Clínica de Acceso a la Justicia",
        "population": "La clínica de emprendimiento atiende a personas interesadas en la revisión de la propiedad intelectual y de sus contratos; todo a través de un socio formador. La clínica de acceso a la justicia también lo hace a través de un socio formador, vinculado con el acceso a la justicia.",
        "title": "Bufetec",
        "objective": "Promover la cultura de la legalidad en el emprendimiento de negocios/el acceso a la justicia.",
        "description": "1. Revisa casos que atiende el socio formador vinculados con aspectos legales\n2. Revisa normatividad para el emprendimiento\n3. Promueve la implementación del derecho en las actividades empresariales",
        "schedule": "Lunes y jueves de 8:00 a 12:00",
        "tags": "LED",
        "abilities": "Compromiso, responsabilidad y dedicación",
        "max": 20,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Campus/zoom",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 12,
        "image": "/bufetec.webp"
    },
    {
        "group": 647,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Cempa Market",
        "population": "Artesanos y artesanas mexicanas de comunidades vulnerables",
        "title": "Digitalizando al mundo artesanal",
        "objective": "Apoyar a artesanos a ser parte del mundo digital por medio de la colaboración con una marca de lujo.",
        "description": "1 .-Toma de fotografías de producto artesanales\n2 .-Redacción de historias de los artesanos \n3 .-Apoyo a artesanos con bocetos de diseños de productos\n4 .-Creación de campañas de comunicación",
        "schedule": "Trabajo por entregables, juntas semanales de acuerdo a horario escolar.",
        "tags": "LAD, LDI, LC, LEM",
        "abilities": "Autodidacta, responsable, empático, autogestión  ",
        "max": 15,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Tec Campus Ciudad de México",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 13,
        "image": "/cempa.webp"
    },
    {
        "group": 611,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Centro de Acción Social Copilco",
        "population": "Jóvenes estudiantes entre 17 y 24 años, ambos sexos\n",
        "title": "Recorriendo un Sendero",
        "objective": "Lograr que alumnos en situación vulnerable termine la preparatoria.",
        "description": "El alumno se presentará a las instalaciones de la Escuela y dará asesoría a los alumnos de la escuela. Impartirá tres materias semanales que se le asignarán al inicio de sus servicio social.\n",
        "schedule": "Lunes a Jueves de 8:00 a 12:00 hrs",
        "tags": "Todas",
        "abilities": "Paciencia y dedicación para que sus alumnos logres entender los Recursos de las materias  que los alumnos están cursando",
        "max": 4,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Luis E. Erro #4. Copilco el Alto. Delegación Coyoacán",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 14,
        "image": "/centro_accion_copilco.jpg"
    },
    {
        "group": 612,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Centro de Autonomía Personal y Social (CAPYS A.C.)",
        "population": "Mujeres y hombres con discapacidad intelectual de 20 años a 65 años ",
        "title": "Vida Independiente para Personas con Discapacidad Intelectual",
        "objective": "Contribuir a la calidad de los servicios que CAPYS proporciona.",
        "description": "1. Participar en una sesión de inducción. \n2. Participar o apoyar directamente en los talleres o actividades.\n3. Participar en el diseño y elaboración de materiales de apoyo.",
        "schedule": "CAPYS trabaja de Lunes a viernes de 9:00 a 18:00 p.m. con flexibilidad de horario.",
        "tags": "Todas",
        "abilities": "Vocación de servicio, empatía, capacidad de adaptación, compromiso, responsabilidad, formalidad, sentido común e iniciativa.",
        "max": 12,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "CAPYS VALLE:  Pilares 310, Col. Del Valle, Alcaldía Benito Juárez, C.P. 03100 CDMX  CAPYS SUR: Camino a Santa Teresa #890 Torre 2, Dpto 101, Magdalena Contreras. ",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 15,
        "image": "/capys.webp"
    },
    {
        "group": 613,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Centro de Desarrollo Empresarial PymesSOS",
        "population": "PyMES",
        "title": "Asesor Pymes SOS Nacional",
        "objective": "Promover la inclusión digital de los dueños de negocios en México. ",
        "description": "1. Realizar sesiones semanales de asesoría con las PyMES para avanzar en las tareas del curso. \n2. Asesorar en temas técnicos de las conexiones por zoom. ",
        "schedule": "Lunes o Martes de 16:00 a 18:00 hrs y Jueves de 16:00 a 18:00 hrs",
        "tags": "Todas",
        "abilities": "Proactividad, espíritu emprendedor, empatía",
        "max": 60,
        "model": "CLIN | Proyecto Solidario en Línea",
        "location": "Zoom ",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 16,
        "image": "/pymes-sos.webp"
    },
    {
        "group": 614,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Centro de Integración Sensorial AC",
        "population": "Personas dentro del Espectro Autista en edades de 4 a 24 años de edad.",
        "title": "Educación integral para personas dentro del Espectro Autista",
        "objective": "Sensibilizar a la población en general con respecto al Espectro Autista.",
        "description": "Sensibilización con respecto al Espectro Autista\nDetección de necesidades básicas de la institución y elaboración de proyectos\nApoyo en las diferentes actividades de la institución",
        "schedule": "lunes a viernes de 9;00 a 1;30 horas.",
        "tags": "Todas",
        "abilities": "Responsabilidad y compromiso",
        "max": 6,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Cerrada Amatista #7 Valle Escondido Tlalpan",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 17,
        "image": "/cisac.webp"
    },
    {
        "group": 615,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Centro Terapéutico Veintiuno x Tres A.C.",
        "population": "Bebés. niños, jóvenes y adultos con Síndrome de Down ",
        "title": "Transforma21",
        "objective": "Movilizar a estudiantes para apoyar integralmente a personas con síndrome de Down y sus familias.",
        "description": "1. Manos a la Obra\n2. Corazones en Acción\n3. Familia 21\n4. Salud y Bienestar\n5. DownForce Creativo\n6. Puentes Comunitarios\n7. Expresión 21",
        "schedule": "Lunes y viernes de 8am a 5:30pm y martes, miércoles y jueves de 8am a 4pm. ",
        "tags": "Todas",
        "abilities": "Empatía y Sensibilidad: Capacidad para entender las necesidades y emociones de las personas con síndrome de Down y sus familias, mostrando empatía y respeto en todo momento.\n\nComunicación Efectiva: Habilidad para comunicarse de manera clara, respetuosa y comprensible, tanto verbalmente como por escrito, con personas de diferentes edades y niveles de habilidad.\n\nTrabajo en Equipo: Capacidad para colaborar efectivamente con colegas, terapeutas, educadores y otros profesionales, contribuyendo al éxito del equipo y al logro de objetivos comunes.\n\nFlexibilidad y Adaptabilidad: Disposición para adaptarse a diferentes situaciones, horarios y necesidades cambiantes dentro del entorno del centro terapéutico.\n\nCreatividad y Creatividad: Habilidad para generar nuevas ideas y soluciones creativas para abordar desafíos y mejorar los programas y servicios ofrecidos a los alumnos.\n\nOrganización y Gestión del Tiempo: Capacidad para planificar y organizar eficientemente tareas y actividades, gestionando de manera efectiva el tiempo y los recursos disponibles.\n\nResolución de Problemas: Habilidad para identificar problemas, analizar situaciones complejas y encontrar soluciones prácticas y efectivas para resolverlos.\n\nÉtica Profesional: Compromiso con altos estándares éticos y profesionales, manteniendo la confidencialidad, el respeto y la integridad en todas las interacciones con los alumnos y sus familias.\n\nCapacidad de Aprendizaje Continuo: Actitud proactiva hacia el aprendizaje y la mejora continua, buscando oportunidades para adquirir nuevos conocimientos y habilidades relacionados con el trabajo en el centro terapéutico.\n\nPasión por el Servicio y la Inclusión: Motivación y dedicación para trabajar en un entorno centrado en el servicio a los demás, con un fuerte compromiso con la inclusión y el bienestar de las personas con síndrome de Down.",
        "max": 12,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Corona boreal #94 bis, colonia prados Churubusco",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 18,
        "image": "/centro_ter_veintiuno_x_tres.webp"
    },
    {
        "group": 616,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "CEPI (Comunidad Educativa y Psicopedagógica Integral)",
        "population": 40,
        "title": "Manejo de TIC's en redes sociales",
        "objective": "Manejar la tecnología y uso de redes en personas con discapacidad.",
        "description": "1. Uso de tecnología de la comunicación e información 2. Manejo de redes sociales",
        "schedule": "Lunes a Viernes de 9:00 A 14:00 hrs",
        "tags": "Todas",
        "abilities": "Responsabilidad, honestidad y respeto a la diversidad.",
        "max": 8,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "CEPI - Mimosa 33 Olivar de los Padres, Álvaro Obregón, 01780, CDMX ",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 19,
        "image": "/cepi.webp"
    },
    {
        "group": 617,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "CIJ Tlalpan",
        "population": "jóvenes y adultos  rango de edad: 12 a 65 años.",
        "title": "Promoviendo Salud Mental en las juventudes. ",
        "objective": "Prevención de adicciones ",
        "description": "Elaboración de material, propuesta de ideas creativas y promoción de la salud. ",
        "schedule": "Lunes, Martes y Viernes de 10:00 a 15:00 hrs",
        "tags": "LNB, LPS",
        "abilities": "Compromiso y proactividad. ",
        "max": 5,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Calle 2 , #10, col. san buenaventura . Esq. Viaducto Tlalpan ",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 20,
        "image": "/cij.webp"
    },
    {
        "group": 618,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Compostec",
        "population": "Alumnos de entre 14 a 26 años, estudiantes del tecnológico de Monterrey, profesores y comunidad tec",
        "title": "Compostec",
        "objective": "Proporcionar a los alumnos una conciencia de consumo responsable mediante la composta.",
        "description": "1) Tomar una capacitación general sobre que es la composta \n2) Participar en una masterclass para aprender a hacer composta\n3)Ir a planta física \n4) Compostar \n5) Documentar el proceso",
        "schedule": "Por acordar con OSF",
        "tags": "Todas",
        "abilities": "Responsabilidad y compromiso",
        "max": 30,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Planta Física del TEC (Ubicada en ES campus CCM)",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 21,
        "image": "/biointellectus.webp"
    },
    {
        "group": 619,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Distrito Tlalpan (DiT)",
        "population": "Comunidades urbanas en el perímetro del Campus CCM",
        "title": "Apoyo al proyecto del distrito Tlalpan",
        "objective": "Apoyo en implementación de iniciativas DiT frente a desafíos sociales de la comunidad.",
        "description": "Apoyar en el desarrollo y la implementación de proyectos de vinculación comunitaria y urbanismo del Distrito Tlalpan",
        "schedule": "Por acordar con OSF",
        "tags": "ARQ, LDI, LTP, LC, IBT, IDS, IDM, LAE",
        "abilities": "Trabajo en equipo, pensamiento crítico, adaptabilidad y creatividad",
        "max": 30,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Distrito Tlalpan (DiT), Campus CCM y alrededores",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 22,
        "image": "/tlalpan.webp"
    },
    {
        "group": 620,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Escuela primaria de tiempo completo \"Somalia\"",
        "population": "Niñas y niños de 6 a 12 años de diversas condiciones y algunos identificados con diversas necesidades de atención especial: con disminución auditiva, autismo moderado, con TDAH, y con dificultades para el aprendizaje.",
        "title": "Construyendo espacios de aprendizaje en Somalia",
        "objective": "Atención a niños con dificultades en aprendizaje y apoyar el funcionamiento de diversos espacios.",
        "description": "1. Apoyar a niños con dificultades en el aprendizaje\n2. Apoyar el funcionamiento de la biblioteca y Aula de Medios \n3. Crear actividades para Ciencia y Matemáticas ",
        "schedule": "Lunes a viernes de (:30 a 15:30",
        "tags": "Todas",
        "abilities": "Responsabilidad, compromiso, solidaridad, propositivo, con disposición a realizar las actividades de forma rotativa",
        "max": 18,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Fortín 46, Unidad Habitacional Narciso Mendoza, Villa Coapa, alcaldía Tlalpan",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 23,
        "image": "/escuela_somalia.jpg"
    },
    {
        "group": 621,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Fundación Burton Blooms I.A.P.",
        "population": "Chicos de escasos recursos económicos y de familias monoparentales donde el jefe de familia es femenino, los beneficiarios son varones de entre 11 y 15 años que cursan la educación secundaria. ",
        "title": "Asesoría a alumnos de secundaria ",
        "objective": "Despertar en nuestros alumnos el gusto por el estudio, como una forma de superación personal ",
        "description": "1.- Asesoría en materias como inglés, computación, matemáticas, química\n2.- Fomentar el enriquecimiento al conocimiento, a la lectura y a los hábitos",
        "schedule": "Lunes a Jueves de 17:00 a 20:00 hrs",
        "tags": "IC, IE, LNB",
        "abilities": "Comunicación",
        "max": 5,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Diligencias 36 col. San Pedro Mártir Tlalpan C.P. 14650",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 24,
        "image": "/burton_blooms.png"
    },
    {
        "group": 648,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Fundación Sue Aguayo A C",
        "population": "Hombres, mujeres y familias a partir de 18 años.",
        "title": "Emprendimientos de éxito en acción",
        "objective": "Fortalecer a emprendedores y sus proyectos con herramientas eficaces y Generar cultura financiera.",
        "description": "1 Diseño de campaña publicitaria \n2 Producción de Videos \n3 Investigación de estrategias financieras \n4 Asesoría financiera\n5 Asesoría de administración de negocios",
        "schedule": "Por acordar con OSF",
        "tags": "ARQ, LC, LAE, LAF, LIN",
        "abilities": "Responsabilidad, compromiso, creatividad, trabajo en equipo, liderazgo, manejar herramientas de diseño y producción de videos.",
        "max": 10,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Calle Barranca Pilares, colonia Pilares Águilas, alcaldía, Álvaro Obregón, Ciudad de México.",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 25,
        "image": "/sue.webp"
    },
    {
        "group": 622,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Hablemos de Bioplásticos - Biointellectus ",
        "population": "Biointellectus atiende una población que no esta diferenciada por edad o genero, ya que ofrecemos una solución a toda persona que busca tener una vida con menos impacto ambiental.",
        "title": "Hablemos De Bioplásticos - Edición audio visual de contenido",
        "objective": "La elaboración de contenido de video largo para la difusión y educación sobre los bioplásticos.",
        "description": "Trabajar principalmente en la edición de audio y video de formato largo, apoyar en las actividades de producción de contenido, revisión de calidad y optimización del contenido.",
        "schedule": "Por acordar con OSF",
        "tags": "LC, LTM",
        "abilities": "Conocimiento de edición de audio y video",
        "max": 10,
        "model": "CLIN | Proyecto Solidario en Línea",
        "location": "Online",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 26,
        "image": "/biointellectus.webp"
    },
    {
        "group": 623,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Hexalud Wellness",
        "population": "Colaboradores con edades de entre 25 y 55 años.",
        "title": "Motivamos a desarrollar hábitos saludables a través de una app mediante un sistema de recompensas",
        "objective": "Ayudar a motivar a los colaboradores en México a desarrollar mejores hábitos saludables.",
        "description": "1. Desarrollo de ideas de mejora para procesos internos (uso de app).\n2. Desarrollo de contenido digital mara manejo de redes sociales.\n3. Investigación sobre temas relacionados a la salud.",
        "schedule": "Lunes a viernes entre 9:00 y 18:00 hrs. (Por acordar).",
        "tags": "LAD, LDI, LC, LNB, LPS, LAF, LDO, LEM",
        "abilities": "Proactividad, trabajo en equipo, responsabilidad, respeto",
        "max": 25,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Tec CCM",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 27,
        "image": "/hexalud.webp"
    },
    {
        "group": 624,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Iniciativa de Educación con Equidad y Calidad - Aprendizajes para Todos.",
        "population": "Jóvenes de 15 a 18 años en media superior pública con rezago educativo",
        "title": "Aprendizajes para Todos",
        "objective": "Brindar tutorías en línea a estudiantes de 15 a 18 años (preparatoria) con rezago académico.",
        "description": "1. Brindar tutorías a estudiantes de preparatoria (4.5 horas a la semana) \n2. Capacitación asincrónica para certificarse como tutor\n3. Bitácoras de planeación y seguimiento",
        "schedule": "Flexible (revisar comentarios)",
        "tags": "Todas",
        "abilities": "1) Compromiso 2) Responsabilidad 3) Disposición de aprender 4) Conocimiento básico de matemáticas y comunicación (español)",
        "max": 200,
        "model": "CLIN | Proyecto Solidario en Línea",
        "location": "NA - En línea",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 28,
        "image": "/ieec.png"
    },
    {
        "group": 625,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Instituto Nacional de Medicina Genómica",
        "population": "Investigación en Salud",
        "title": "Fortalecimiento de las actividades de la Institución",
        "objective": "Divulgación enfermedades crónicas.",
        "description": "Las actividades pueden variar dependiendo el área donde estará apoyando el estudiante, puede ser desde investigación, divulgación, comunicación, administrativo.",
        "schedule": "Por acordar con OSF (4 horas diarias, como mínimo,  de lunes a viernes).",
        "tags": "LAD, LDI, LED, LC, LPE, ITC",
        "abilities": "Entusiasmo por aprender, compromiso en asistir y trabajar en equipo",
        "max": 15,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Instalaciones del INMEGEN",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 29,
        "image": "/inmg.webp"
    },
    {
        "group": 627,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "La Casita de San Ángel IAP",
        "population": "La Casita de San ángel atiende a personas adultas mayores de 18 años con discapacidad intelectual",
        "title": "Inclusión educativa en personas con discapacidad intelectual",
        "objective": "Misión: promover valores de contenido social: educativos, recreativos, filantrópicos y culturales para el desarrollo social del individuo, su familia y su comunidad en espíritu, mente y cuerpo",
        "description": "1-Impartir taller formativo para desarrollar y reforzar habilidades sociales y laborales\n2-Material visual y didáctico\n3-Material de medición de conocimiento",
        "schedule": "Lunes a viernes de 9:00 a 17:00 hrs",
        "tags": "Todas",
        "abilities": "Creatividad, escucha, expresión incluyente, asertividad.",
        "max": 10,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Heriberto Frías #215 Col Narvarte CP 03020, Alcaldía Benito Juárez ",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 31,
        "image": "/casita_angel.jpg"
    },
    {
        "group": 626,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "La Casita de San Ángel IAP",
        "population": "La Casita de San ángel atiende a personas adultas mayores de 18 años con discapacidad intelectual",
        "title": "Fuerza Digital Inclusiva",
        "objective": "Tener un gran alcance para las personas que requieran el servicio  de la OSF ,aumentar  voluntariado",
        "description": "1.- Revisar las redes sociales con las que contamos\n2.- Propuestas para de rediseño,  innovación y actualización \n3.- Realizar un manual de uso de redes para OSF",
        "schedule": "Lunes a viernes de 9:00 a 17:00 hrs",
        "tags": "LAD, LDI, LEI, ITC, ITD, IID",
        "abilities": "Creatividad, escucha, expresión incluyente, asertividad",
        "max": 5,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Heriberto Frías #215 col Narvarte CP 03020, Alcaldía Benito Juárez",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 32,
        "image": "/casita_angel.jpg"
    },
    {
        "group": 628,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Módulo Deportivo San Nicolas Tolentino",
        "population": "Toda la ciudadanía en general.",
        "title": "Cursos gratuitos en apoyo a la ciudadanía ",
        "objective": "Aplica conocimientos a la ciudadanía por medio de la aplicación de cursos gratuitos.",
        "description": "1. Definir necesidades y cursos gratuitos a impartir (por ejemplo: idiomas o computación)\n2. Cumplir con los horarios establecidos\n3. Impartir talleres con mucha responsabilidad y empatía",
        "schedule": "Lunes a Viernes de 9:00 a 18:00 hrs.  y Sábados de 9:00 a 14:00 hrs.",
        "tags": "Todas",
        "abilities": "Responsabilidad y empatía",
        "max": 15,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Hacienda San Nicolás Tolentino s/n, Coapa, Prado Coapa, Tlalpan, 14357 Ciudad de México, CDMX",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 33,
        "image": "/tlalpan.webp"
    },
    {
        "group": 630,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Observatorio de Desarrollo Regional y Promoción Social A. C.",
        "population": "Personas en estado de vulnerabilidad social, independientemente de su edad o sexo",
        "title": "Actualización del Sistema de Información Estadística de Gobernabilidad y Desarrollo",
        "objective": "Apoyar en el desarrollo y actualización del Sistema de Información Estadística de ODP",
        "description": "1. Contribuir a actualizar el Sistema de Información. 2. Proponer nuevos indicadores. 3. Detectar actores, redes y eventos relevantes relacionados a las variables de interés",
        "schedule": "Por acordar con OSF",
        "tags": "LEC, LED, LRI, LTP, LC, LPE, IDS, LDE",
        "abilities": "Se busca que los alumnos estén comprometidos a trabajar constantemente a lo largo de todo el semestre. Se requiere que los alumnos cuenten con facilidad para el razonamiento lógico y capacidad de observación y entendimiento de los fenómenos sociales, políticos económicos y jurídicos; que tengan experiencia en manejo de bases de datos o que estén dispuestos a aprender sobre la organización de dichas bases.",
        "max": 10,
        "model": "CLIN | Proyecto Solidario en Línea",
        "location": "A distancia",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 35,
        "image": "/odrps.png"
    },
    {
        "id": 58,
        "organization": "Escuela Primaria \"Ucrania\"",
        "population": "El 95 % de la población son alumnos regulares",
        "title": "Formación de mejores ciudadanos",
        "objective": "Apoyar el desarrollo académico de niños de primaria",
        "description": "1. Ayuda a los docentes en su labor \n2. Apoyo a las actividades de la escuela \n3. Elaboración de materiales cuando el docente se los requiera (son de fácil elaboración)",
        "schedule": "Lunes a viernes de 8:00 a 16:00 hrs.",
        "tags": "Todas las carreras",
        "abilities": "Disposición y ganas de trabajar",
        "max": 25,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Andador 62 de Avenida Acoxpa, número 63 Supermanzana 6, Villa Coapa, Tlalpan",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "image": "/sep.jpg",
        "group": 661,
        "key": "WA1058"
    },
    {
        "group": 219,
        "key": "WA1071",
        "implementation_date ": "24 de junio al 26 de julio",
        "organization": "Violines por la Paz A.C. ",
        "population": "infancias en situación vulnerable ",
        "title": "Psicología y nutrición para infancias",
        "objective": "Realizar entrevistas nutricionales y psicopedagógicas a infancias",
        "description": "1. Entrevistar e interpretar perfiles nutricionales y psicológicos",
        "schedule": "Flexible",
        "tags": "LNB, LPS",
        "abilities": "Habilidades con infancias, conocimiento en nutrición o psicología.",
        "max": 20,
        "model": "CLIP | Proyecto Solidario Mixto (presencial y virtual)",
        "location": "En caso de actividades presenciales: TEC CCM .",
        "duration": "5 semanas",
        "hours": "200",
        "extra_coments": "Revisar modalidad, lugar de trabajo y horarios",
        "id": 44,
        "image": "/violines.webp"
    },
    {
        "group": 220,
        "key": "WA1071",
        "implementation_date ": "24 de junio al 26 de julio",
        "organization": "Vive Planeta",
        "population": "Realmente va enfocado a jóvenes entre 17 - 30 años.",
        "title": "¡Cambiemos el mundo poco a poco! ",
        "objective": "Visibilizar y accionar ante problemáticas sociales y ambientales. ",
        "description": "Desarrollo de contenido de cultura ambiental por medio de la realización de investigaciones (1 cuartilla por tema) de alguna problemática social/ambiental y además un video de 1 min, alrededor de 5 por semana y edición de videos para el podcast Voces en Acción",
        "schedule": "Por acordar con la organziación",
        "tags": "LAD, LDI, LRI, LC, LPE",
        "abilities": "Conocimiento y uso de Photoshop o illustrator, imovie o herramientas para edición de videos, canva, capcut, inshot, etc. Tener la habilidad de investigar de fuentes fidedignas y de resumir la información.",
        "max": 8,
        "model": "CLIP | Proyecto Solidario Mixto (presencial y virtual)",
        "location": "En sus casas y puede ser en algún lugar público cuando haya evento. ",
        "duration": "5 semanas",
        "hours": "200",
        "extra_coments": "Para este servicio es necesario que se unan jóvenes interesadas(os) y comprometidos(as) en hacer un cambio en la sociedad y en el medio ambiente. ",
        "id": 45,
        "image": "/vive-planeta.webp"
    },
    {
        "group": 120,
        "key": "WA1070",
        "implementation_date ": "24 de junio al 26 de julio",
        "organization": "De Aprendices Para Aprendices (DAPA)",
        "population": "Hispanohablantes de todas las edades y géneros, pertenecientes a segmentos socioeconómicos de clase media-baja y baja, que enfrentan limitaciones en el acceso a la educación y que tienen un dispositivo móvil con internet.",
        "title": "¡Mejora tu Inglés Compartiendo lo que Sabes!",
        "objective": "Ayudar a las personas a aprender inglés según su nivel, con el fin de tener un progreso en el idioma.",
        "description": "1. Dar clases de inglés en sesiones de 1 a 1.\n2. Asistir a zooms: introducción, retroalimentación, cierre\n3. Aplicar exámenes diagnósticos y crear temarios y materiales\n4. Acordar horarios con el aprendiz y registrar asistencias y tareas.",
        "schedule": "Por acordar con la organziación",
        "tags": "Todas",
        "abilities": "Empatía, responsabilidad, respeto, compromiso, comunicación asertiva, participación activa, habilidades matemáticas y de comprensión de lenguaje básicas, liderazgo. ",
        "max": 23,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Yácatas 418, 03020, Ciudad de México, México",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 36,
        "image": "/pas.webp"
    },
    {
        "group": 633,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Programa YMCA de desarrollo comunitario y asistencia social",
        "population": "Niñas y niños regulares de 3 a 5 años y jóvenes y adultos con discapacidad intelectual de 15 a 40 años.",
        "title": "Hábitos de vida saludable",
        "objective": "Realizar taller para promover hábitos saludables y mejorar la calidad de vida",
        "description": "1. Inducción 2. Observación 3.Investigación, planeación y generación de actividades  4.Implementación de actividades con la población 5. Entrega, retroalimentación y cierre ",
        "schedule": "Por acordar con los prestadores de servicio social",
        "tags": "Todas, LNB, LPS",
        "abilities": "Creatividad, manejo de groups, sociabilidad, iniciativa, facilidad de palabra.",
        "max": 10,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Canal de Othenco No. 162 Colonia Santiago Norte, Alcaldía Iztacalco CP 08240 CDMX",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 38,
        "image": "/ymca.webp"
    },
    {
        "group": 651,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Red para la Restauración Integral y Familiar AC",
        "population": "Actualmente atendemos a 25 niñas y niños  entre 4 y 13 años; y 30 adolescentes de 14 a18 años,  de diversas alcaldías, como: Tlalpan, Coyoacán, Xochimilco, y Tláhuac. Tenemos niños con déficit de atención, TDA, autismo, así como algunos que han sufrido bullying. Les brindamos asesoría académica y regularización, trabajando con la didáctica adecuada para mejorar su calidad de vida y lograr un desarrollo integral. ",
        "title": "Preparando generaciones en estatura, sabiduría y gracia",
        "objective": "Consolidar el primer Centro de Desarrollo Integral Familiar (CEDIFAM), para apertura de  más CEDIFAM",
        "description": "Brindarán capacitación en el idioma inglés, francés, español y otras materias según su perfil académico.\nRegularización de materias como: matemáticas, química, etc.\nApoyo a docentes en áreas diversas.",
        "schedule": "Lunes a Viernes 9:00 am  a 14:00 hrs",
        "tags": "Todas",
        "abilities": "Interactuar con calidez con niñas, niños y adolescentes. Impartiendo conocimientos ajustándonos al sistema, ACE_LAM.",
        "max": 15,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Arbusto 99 Col. Las Hadas Coapa Tlalpan CP 14390",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 39,
        "image": "/rifac.webp"
    },
    {
        "group": 634,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "SOS Climático, divulgación y análisis A.C. ",
        "population": "Hombres y mujeres jóvenes en zonas urbanas y conurbadas.CDMX.\nComunidades rurales en el Estado de Guerrero.",
        "title": "Nuestro Planeta es nuestra casa. Ayúdala!",
        "objective": "Divulgación, sensibilización por el Cambio Climático y creación de una cultura por el Medioambiente",
        "description": " Creación de contenidos dirigidos a jóvenes en nuestras redes sociales\nMejoramiento de nuestro sitio web\nCreación e implementación de Talleres para alumnos de 6 a 14 años en zonas rurales.",
        "schedule": "Por acordar con OSF junta semanal",
        "tags": "LDI, LC, LEI, LPE, IDS, IDM, IRS, ITC, ITD, IID, LEM",
        "abilities": "Responsabilidad por la naturaleza y la vida, creatividad para transmitir nuestros mensajes, Carreras a fines a la Comunicación, Diseño, programación de RRSS",
        "max": 20,
        "model": "CLIN | Proyecto Solidario en Línea",
        "location": "Desde su casa",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 40,
        "image": "/sos.webp"
    },
    {
        "group": 653,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Fundación Sue Aguayo A C",
        "population": "Niños, jóvenes, adultos con discapacidad, en orfandad y familias de bajos recursos",
        "title": "Campaña de publicidad, producción  y difusión: cenas navideñas 2024.",
        "objective": "Sensibilizar a la sociedad  PARA COMPARTIR la cena de navidad, con personas de bajos recursos ",
        "description": "1. Producción y edición de Videos, podcast. 2 diseño de flyers y logotipos. 3 Redacción de cartas e invitaciones.",
        "schedule": "Flexible ",
        "tags": "ARQ, LC",
        "abilities": "Creatividad, liderazgo, compañerismo, positivismo, responsabilidad. Manejar herramientas de diseño y producción audiovisual.",
        "max": 10,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Calle Barranca Pilares, colonia Pilares Águilas, alcaldía Álvaro Obregón, ciudad de México.",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 41,
        "image": "/sue.webp"
    },
    {
        "group": 636,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Tecnológico de Monterrey",
        "population": "Jóvenes",
        "title": "Biotecnología",
        "objective": "Llevar a cabo un programa de divulgación e investigación científica para el desarrollo social.",
        "description": "Investigación documental; trabajo experimental (IBT); visitas de campo; procesamiento de datos; monitoreo y seguimiento de actividades; colaboración en divulgación, RR.SS. y eventos; apoyo general.",
        "schedule": "Por acordar con OSF entre lunes y viernes",
        "tags": "IAG, IAL, IBT",
        "abilities": "Antes de inscribirse, enviar un correo a info@sebiotecmx.org para verificar la disponibilidad de vacantes. Habilidades y competencias requeridas: redacción y ortografía adecuadas para la investigación científica; aptitudes para lectura y escritura académicas; manejo de paquetería Office; disponibilidad para reuniones virtuales o presenciales entre una y tres veces por semana por la mañana o tarde. ",
        "max": 15,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Edificio CIEE del TEC Campus Ciudad de México o a convenir con la OSF",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 42,
        "image": "/tec-logo.webp"
    },
    {
        "group": 652,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Tecnológico de Monterrey, Licenciatura en Tecnología y Producción Musical CCM",
        "population": "Agrupaciones musicales y culturales de diversas edades (principalmente mayores de edad) quienes tienen poco o nulo acceso a estudios de grabación profesionales.",
        "title": "Sesiones de grabación para el apoyo y fomento de la cultura",
        "objective": "Propiciar el rescate cultural y mediante el registro en grabaciones musicales",
        "description": "1. Lanzamiento de convocatoria. 2. Sesión de inducción 3. Estructuración de equipos de trabajo 4. Capacitación para alumnos 5. Sesiones de grabación. 6. Sesiones de retroalimentación. 7. Entrega final",
        "schedule": "Miércoles y/o Viernes de 15:00 a 21:00 hrs",
        "tags": "LTM",
        "abilities": "Resolución de problemas, adaptación al cambio, liderazgo, sentido humano, trabajo en equipo, logística, conocimientos técnicos (audiovisuales, microfonía, manejo de consolas de audio)",
        "max": 30,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Tec CCM, Estudios de grabación en CIEE primer piso",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 43,
        "image": "/tec-logo.webp"
    },
    {
        "group": 637,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Tus Buenas Noticias",
        "population": "Jóvenes + mujeres + hombres",
        "title": "Speak Up: transformando la ciudad con buenas noticias",
        "objective": "Elaboración de contenido positivo para la reducción de la fatiga de información ",
        "description": "1. Capacitación Periodismo Constructivo \n2. Seleccionar de temas \n3. Investigar información \n4. Elaborar el artículo y/o video pertinente\n5. Enviar a revisión\n",
        "schedule": "Lunes a Viernes de 8:00 a 12:00 hrs",
        "tags": "Todas, LC, LPE",
        "abilities": "Buena ortografía\nProactividad\nGusto por la escritura basada en historias que inspiran y noticias positivas\n",
        "max": 10,
        "model": "CLIN | Proyecto Solidario en Línea",
        "location": "",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 44,
        "image": "/noticias.webp"
    },
    {
        "group": 638,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Escuela Primaria Ucrania ",
        "population": "Niños y niñas de entre 6 y 12 años",
        "title": "Por una mejor educación ",
        "objective": "Mejorar la  calidad educativa de nuestros alumnos ",
        "description": "1. Apoyo a la labor docente  2. Elaboración de materiales en la computadora",
        "schedule": "Lunes a Viernes de 8:00 a 16:00 hrs",
        "tags": "Todas",
        "abilities": "Manejo de la computadora, disposición al trabajo ",
        "max": 25,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Andador 62 de avenida Acoxpa SMZ VI Villa Coapa ",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 45,
        "image": "/sep.jpg"
    },
    {
        "group": 639,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Un techo para mi país",
        "population": "Familiar de todas las edades en situación de pobreza extrema, que viven en asentamientos populares con falta de al menos un servicio básico.",
        "title": "Gestión y fortalecimiento comunitario",
        "objective": "Promover el desarrollo comunitario en asentamientos populares.",
        "description": "1. Gestionar mesas de trabajo de adultos en nuestras comunidades\n2. Diagnosticar necesidades claves para cada una de las comunidades\n3. Implementar proyectos del área de vivienda y hábitat",
        "schedule": "Sábados y/o Domingos aproximadamente de 8:00 am a 14:00 hrs",
        "tags": "Todas",
        "abilities": "Liderazgo, trabajo en equipo, escucha activa, gestión de conflictos",
        "max": 17,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Según la comunidad a la que asistan, la mayoría son al sur",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 46,
        "image": "/techo.webp"
    },
    {
        "group": 640,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Una Mirada Rett A.C.",
        "population": "Niñas de 0 a 12 que tengan Síndrome de Rett y a Familiares que son cuidadores primarios  y Voluntarios que promueven  la inclusión social.",
        "title": "Responsabilidad Social y Alianzas por las infancias",
        "objective": "Promover los derechos humanos de los niños y alianzas que ayuden a Niñas con S.Rett",
        "description": "Investigación de condiciones de infancia en México, elaboración de materiales de difusión, alianzas estratégicas para el desarrollo de niñas",
        "schedule": "Lunes a viernes de 9:00 a 13:00 hrs",
        "tags": "LDI, LEC, LRI, LTP, LC, LPE, LPS, LAE, LAF, LEM, LIN",
        "abilities": "Proactivo, trabajo en equipo, pensamiento creativo...",
        "max": 16,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Emiliano Zapata 75, Col. Portales Norte, Alcaldía Benito Juárez 03303",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 47,
        "image": "/mirada-rett.webp"
    },
    {
        "group": 641,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Unidos Somos Iguales ",
        "population": "Personas con y sin discapacidad, de los 15 a los 30 años,  discapacidad intelectual, motriz, auditiva, social. ",
        "title": "Otoño Días de Rol ",
        "objective": "Aumentar la participación social de las personas con discapacidad. ",
        "description": "1. Acompañamiento en actividades recreativas\n2. Participación activa en todo momento \n3. Liderazgo \n4. Apertura  ",
        "schedule": "Sábados de 9:00 a 15:00 hrs",
        "tags": "Todas",
        "abilities": "Empatía, liderazgo, apertura al cambio, sensibilidad",
        "max": 5,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Lugar de las actividades ",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 48,
        "image": "/unidos.png"
    },
    {
        "group": 642,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Violines por la paz a.c.",
        "population": "Infancias en situación vulnerable",
        "title": "Docencia para el desarrollo de talento",
        "objective": "Impartir clases de talento a infancias ",
        "description": "1. Plan de clase, 2. Impartir clase en diferentes áreas ",
        "schedule": "Flexible",
        "tags": "Todas",
        "abilities": "Habilidades en docencia, conocimiento de la materia a impartir",
        "max": 20,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Somalia o Tec. de Monterrey",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 49,
        "image": "/violines.webp"
    },
    {
        "group": 643,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Violines por la paz A.C. ",
        "population": "Infancias en situación de vulnerabilidad ",
        "title": "Psicología y nutrición para niños ",
        "objective": "Desarrollar autonomía en torno a su salud nutricional/emocional",
        "description": "1. Plan de trabajo de conferencias de psicología y nutrición para niños 2. Diseño de talleres 3. Impartición de talleres",
        "schedule": "Flexible",
        "tags": "LNB, LPS",
        "abilities": "Conocimientos en nutrición o psicología, gusto por las infancias, habilidades de docencia",
        "max": 10,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Instalaciones del tecnológico de monterrey y primaria Somalia ",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 50,
        "image": "/violines.webp"
    },
    {
        "group": 644,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Vive Planeta",
        "population": "Jóvenes",
        "title": "Creando consciencia con Vive Planeta",
        "objective": "Visibilizar, cuestionar y accionar ante los problemas sociales y ambientales que enfrentamos. ",
        "description": "Generar videos y guiones sobre medio ambiente y los derechos humanos.\nInvestigar sobre problemáticas sociales, alternativas eco friendly, movimientos sociales, noticias ambientales relevantes, etc. ",
        "schedule": "Por acordar con OSF",
        "tags": "LAD, LDI, LRI, LC, LPE",
        "abilities": "Conocimiento y uso de Photoshop o illustrator, imovie o herramientas para edición de videos, canva, capcut, inshot, etc. Tener la habilidad de investigar de fuentes fidedignas y de resumir la información. ",
        "max": 10,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Por definir pero podría ser en un lugar público. ",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 51,
        "image": "/vive-planeta.webp"
    },
    {
        "group": 654,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Pädi",
        "population": "Estudiantes de 11 a 18 años de México que busquen complementar su aprendizaje y que cuenten con disposición mínima para sostener internet.",
        "title": "Plataforma de asesoramiento académico Pädi",
        "objective": "Crear enfoque donde colaboración y personalización del aprendizaje sean los pilares para triunfar",
        "description": "1. Desarrollo tecnológico de plataforma web 2. Creación de material didáctico para la plataforma 3. Creación de material de marketing para la difusión de los proyecto",
        "schedule": "Actividades asincrónicas",
        "tags": "Todas",
        "abilities": "Liderazgo, compromiso, responsabilidad y trabajo en equipo.",
        "max": 15,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Híbrido con posibilidad a reuniones presenciales dentro de CCM",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 52,
        "image": "/padi.webp"
    },
    {
        "group": 657,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "De Aprendices Para Aprendices (DAPA)",
        "population": "DAPA beneficia a hispanohablantes de todas las edades y géneros, pertenecientes a segmentos socioeconómicos de clase media-baja y baja, que enfrentan limitaciones en el acceso a la educación y que tienen un dispositivo móvil con internet.",
        "title": "¡Mejora tu Inglés Compartiendo lo que Sabes!",
        "objective": "Ayudar a las personas a aprender inglés según su nivel, con el fin de tener un progreso en el idioma",
        "description": "1. Participar y coordinar sesiones de clases de inglés\n2. Aplicar exámenes (cada quien tendrá 2 aprendices)\n3. Preparar temario y material\n4. Registrar asistencias y tareas",
        "schedule": "Se coordinará con cada aprendiz (horario flexible)",
        "tags": "Todas",
        "abilities": "1. Saber utilizar paquetería de Google (Drive, Google Docs, Google Sheets y Formularios de Google), así como la plataforma de Zoom.\n2. Buena comunicación tanto con personas de su misma edad, como con infantes y personas mayores.\n3. Buena organización, paciencia y facilidad para la resolución de problemas.\n4. Nivel B2 de inglés",
        "max": 12,
        "model": "CLIN | Proyecto Solidario en Línea",
        "location": "En línea",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 53,
        "image": "/dapa.webp"
    },
    {
        "group": 658,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "De Aprendices Para Aprendices",
        "population": "DAPA beneficia a hispanohablantes de todas las edades y géneros, pertenecientes a segmentos socioeconómicos de clase media-baja y baja, que enfrentan limitaciones en el acceso a la educación y que tienen un dispositivo móvil con internet.",
        "title": "EcoAcción Mensual: Sembrando Conciencia",
        "objective": "Realizar actividades ecológicas y organizar una plática sobre ecología a una casa hogar/ escuela.",
        "description": "1. Asistir a sesiones de zoom \n2. Realizar actividades con fines de ayuda ecológica cada 3 semanas \n3. Organizar una plática de algún tema ecológico a escuela/casa hogar\n4. Reflexión final escrita",
        "schedule": "Horario flexible",
        "tags": "Todas",
        "abilities": "1. Saber utilizar paquetería de Google (Drive, Google Docs, Google Sheets y Formularios de Google), así como la plataforma de Zoom.\n2. Buena comunicación tanto con personas de su misma edad, como con infantes y personas mayores.\n3. Buena organización, paciencia y facilidad para la resolución de problemas.\n4. Apertura para desaprender y reaprender",
        "max": 15,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "En línea y presencial en una escuela o casa hogar que ellos escojan",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 54,
        "image": "/dapa.webp"
    },
    {
        "group": 655,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Fundación Bull&Bear",
        "population": "Infancias, adolescentes, Jóvenes con discapacidad intelectual, Adultos Mayores y Migrantes.",
        "title": "Acompañamiento psico-social para la población vulnerable en la Ciudad de México",
        "objective": "Generar estrategias creativas de acompañamiento psico-social para población vulnerable en CDMX",
        "description": "Creación de contenido y diseño de talleres didácticos.\nImpartir talleres creados y diseñados por alumnos.\nDiseño para redes sociales de la Fundación.\n",
        "schedule": "Híbrido",
        "tags": "LAD, LC, LEI, LTM, IDM, LPS",
        "abilities": "Trabajo en equipo, disposición, empatía, gusto por proyectos sociales",
        "max": 6,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "Home Office y Casas Hogares",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 55,
        "image": "/bull_and_bear.webp"
    },
    {
        "group": 659,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Summa Terra CCM",
        "population": "Personas en situación de movilidad que se encuentren en algún refugio o albergue para migrantes, desde menores de edad y mamás embarazadas, hasta generalmente mujeres y hombres entre los 30 y 40 años de edad.\n",
        "title": "Creación de estrategias digitales para compartir una migración humana.",
        "objective": "Crear una campaña de posicionamiento digital de RRSS y página web para maximizar el impacto online.",
        "description": "1. Crear ideas de impacto social para la creación de contenido.\n2. Personalizar la página web que presuman a la OSF como una iniciativa de valor.\n3. Edición de posts, reels y tiktoks llamativos.",
        "schedule": "",
        "tags": "LAD, LDI, LC, LTM",
        "abilities": "Compromiso, empatía, creatividad, proactividad y liderazgo",
        "max": 15,
        "model": "CLIP | Proyecto Solidario Mixto",
        "location": "TEC CCM",
        "duration": "15 semanas (hasta 180 hrs)",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 56,
        "image": "/summa-terra.webp"
    },
    {
        "group": 663,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Progracademy",
        "population": "Niñas y niños en edad escolar, de 8 a 14 años, en situación vulnerable",
        "title": "Líderes Entrenadores de los Programadores del Futuro",
        "objective": "Disminuir la brecha digital e inclusión de las niñas en el área tecnológica",
        "description": "Entrenamiento: Coaching, Liderazgo y metodología Progracademy Implementación de cursos y tecnologías Revisión de desempeño con MC Evaluación de sesiones de estudiantes para el mejoramiento del programa",
        "schedule": "Lunes a viernes entre las 6:00 y 17:00 hrs (programa de modalidad virtual)",
        "tags": "Todas",
        "abilities": "Habilidades de Comunicación,\nOrganización y Gestión del Tiempo,\nEmpatía y Paciencia,\nFlexibilidad y Adaptabilidad,\nPasión por la Enseñanza,\nHabilidades de Evaluación: Capaz de diseñar y aplicar seguimiento efectivo que mida el progreso del estudiante de manera justa y constructiva,\nComprometido con el aprendizaje y la mejora continua, \nCreatividad e imaginación.\nDebe ser competente en el uso de diversas plataformas tecnológicas de uso común (Microsoft Office, WhatsApp), así como en el manejo de herramientas de videoconferencia. No es necesario que sepa programar, pero sí estar dispuesto a aprender.",
        "max": 40,
        "model": "CLIN | Proyecto Solidario en Línea",
        "location": "Programa en línea",
        "duration": "15 semanas (hasta 180 hrs)",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 57,
        "image": "/progracademy.webp"
    },
    {
        "group": 102,
        "key": "WA1065",
        "implementation_date": "5 de agosto - 6 de septiembre 2024",
        "organization": "Comisaría Preventiva Municipal de El Salto",
        "population": "Niñas, Mujeres Víctimas de Violencia",
        "title": "Sistema educativo generacional, Violencia generacional, ideologías machistas, falta de oportunidades a nivel educativo y empleo (juventudes asertivas)",
        "objective": "Visibilizar y Prevenir violencias con perspectiva de género.",
        "description": "1. Capacitar sobre juventudes asertivas\n2. Vincular\n3. Asesorar\n4. Atender\n5. Acompañar",
        "schedule": "Lunes a viernes entre las 8:00 y 12:00 hrs",
        "tags": "Todas",
        "abilities": "Interés de trabajar en favor de la restitución humana",
        "max": 20,
        "model": "CLIN | Proyecto Solidario en Línea",
        "location": "La capacitación es por zoom",
        "duration": "5 semanas",
        "hours": "Hasta 60",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 59,
        "image": "/comisaria_el_salto.jpg"
    },
    {
        "group": 661,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 6 de septiembre 2024",
        "organization": "Lazos I.A.P.",
        "population": "Atendemos a 22,000 alumnos de escuelas primarias y secundarias púbicas en contexto de vulnerabilidad, que se encuentran en 80 primarias y 18 secundarias en 25 estados de la República Mexicana. Capacitamos en talles de crianza positiva y responsable a más de 18,000 padres de familia, así mismo capacitamos con diferentes estrategias como clínicas, encuentros nacionales, y talleres presenciales a más de 1,000 maestros.",
        "title": "Engagement and Social Marketing",
        "objective": "Generar una estrategia de engagement y social marketing para mantener aliados estratégicos.",
        "description": "1.-Analisis e investigación de estrategias actuales de Lazos con herramientas como FODA\n2.- Apoyo en elaboración de benchmarketing digital\n3.- Apoyo en elaboración de 1 a 3 estrategias de engagement.",
        "schedule": "Por acordar con OSF",
        "tags": "Todas",
        "abilities": "Habilidad verbal, creatividad e innovación",
        "max": 30,
        "model": "CLIN | Proyecto Solidario en Línea",
        "location": "Trabajo virtual",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 60,
        "image": "/lazos.webp"
    },
    {
        "group": 660,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 6 de septiembre 2024",
        "organization": "Bienestar Estudiantil TEC CCM",
        "population": "comunidad Tec de Monterrey en CCM",
        "title": "Brigada Emocional",
        "objective": "Brindar contención parcial para quienes presenten una crisis dentro de la institución.",
        "description": "\"Presencialidad en eventos, actividades. \nGeneración de contenido para radio (Concepto Radial) \nCobertura de guardias presenciales  \"",
        "schedule": "Por acordar con OSF",
        "tags": "LPS",
        "abilities": "Alumna activa de la carrea de Psicología a partir del 5° semestre. \n\nProactiva, empática y con habilidades que denoten su liderazgo. \n\nCapacidad para comunicarse de manera asertiva. \n\nConocimientos básicos de PAP \n\nTener acreditadas las capacitaciones de Testigo Activo y QPR. \n\nNo tener antecedentes en Conducta Estudiantil, en CRDH y en Integridad académica.",
        "max": 7,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "TEC CCM",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 61,
        "image": "/bienestar-estudiantil.webp"
    },
    {
        "group": 103,
        "key": "WA1065",
        "implementation_date": "5 de agosto - 6 de septiembre 2024",
        "organization": "Asociación Mexicana de Ayuda a Niños con Cáncer IAP.",
        "population": "Población con diferentes tipos de cáncer, edad: 0 a 18 años, masculino y femenino, con diferentes discapacidades, de pendiendo el tipo de cáncer. ",
        "title": "Generando redes sociales",
        "objective": "Es general redes de apoyo para que AMANC continúe ayudado a más NNA con cáncer. ",
        "description": "1- Apoyo en eventos para procuración de recursos 2- Apoyo operativo 3- Actividades recreativas con beneficiarios ",
        "schedule": "Por acordar con OSF",
        "tags": "Todas",
        "abilities": "Proactivo, Solución del Problema, Comunicación, Iniciativa, etc. ",
        "max": 10,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "En Centro AMANC(Magisterio Nacional No. 100, col. Centro Tlalpan) puede ser otro lugares",
        "duration": "5 semanas",
        "hours": "Hasta 60",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 62,
        "image": "/amanc.webp"
    },
    {
        "group": 669,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Asociación de Nutrición y Salud Biológica A.C",
        "population": "Población vulnerable a contraer enfermedad no transmisible derivada del estilo de vida moderno (sedentarismo, alimentación etc.)",
        "title": "Creación de software para monitoreo de salud y comportamiento saludables por medio de wereables.",
        "objective": "Promover estilo de vida saludable mediante tecnología e innovación social.",
        "description": "1. Programación de tableros de indicadores 2. Dar soporte en los procesos de apoyo 3. Análisis estadístico de la información 4. Generación de reportes. ",
        "schedule": "a sincrónico",
        "tags": "ITC, IMD",
        "abilities": "Programacion y Código en react",
        "max": 4,
        "model": "CLIN | Proyecto Solidario en Línea",
        "location": "Online (opcional reuniones en cmpus ccm)",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 63,
        "image": ""
    },
    {
        "group": 666,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "The Pueblito ",
        "population": "Pymes en la cdmx que venden productos físicos, pequeños ",
        "title": "App de Envíos para Pymes",
        "objective": "Llegar a más de 20 Pymes",
        "description": "1. Desarrollo de App 2. Implementacion de Soluciones como Chatbots y Automatizaciones 3. Creación de Contenido 4. Optimizacion de Página Web",
        "schedule": "Flexible, tentativo 12 a 4 pm",
        "tags": "ITC, ITD, LAE, LDE, LEM, LIT",
        "abilities": "Para app saber programar y Para las demás Proactivos, Aportar nuevas ideas, Responsabilidad y Persistencia",
        "max": 12,
        "model": "CLIN | Proyecto Solidario en Línea",
        "location": "Remoto ",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 64,
        "image": "/pueblito.webp"
    },
    {
        "group": 670,
        "key": "WA3020",
        "implementation_date": "5 de agosto - 30 de noviembre 2024",
        "organization": "Asociación Mexicana de Artesanos con Discapacidad (Amigarte) ",
        "population": "Personas con discapacidad y adultos mayores",
        "title": "Amigarte: Feria de artesanos con discapacidad",
        "objective": "Promover el trabajo artesanal hecho por personas con discapacidad.",
        "description": "Organizar una feria donde personas con discapacidad ofrezcan sus productos y documentar el evento.",
        "schedule": "Lunes y jueves de 10:00 a 14:00",
        "tags": "Todas, LC, ITC",
        "abilities": "Capacidad para movilizarse en la ciudad para visitar organizaciones o personas en caso necesario. Socializar con personas. Tomar fotografías, grabar video, redactar testimonios.",
        "max": 30,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Dentro y fuera del Campus Ciudad de México, se requieren visitas a organizaciones.",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 65,
        "image": "/amigarte.webp"
    },
    {
        "group": 109,
        "key": "WA1065",
        "implementation_date": "5 de agosto - 6 de septiembre 2024",
        "organization": "Ampre",
        "population": "Personas con discapacidad",
        "title": "Maiasa - Ampre: Sociabilización inclusiva y desarrollo humanitario",
        "objective": "Proporcionar los integrantes de nuestra comunidad: talleres, herramientas, conocimientos y mentoría.",
        "description": "1. Participar en el curso de Liderazgo\n2. Realizar assessments de autoevaluación\n3. Trabajar un proyecto en equipo\n4. Participar en las actividades sabatinas dentro de nuestra institución",
        "schedule": "Sábados 10:30 a 13:30",
        "tags": "Todas",
        "abilities": "Creatividad, Liderazgo, Empatía, Pensamiento Incluyente, Actitud Positiva y Compromiso.",
        "max": 20,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Ahuacan 8, Cantera Puente de Piedra, Tlalpan, 14040 Ciudad de México, CDMX",
        "duration": "5 semanas",
        "hours": "Hasta 60",
        "extra_comments": "Revisar modalidad, lugar de trabajo y horarios del proyecto solidario para escoger la opción que más se acople a tus necesidades.",
        "id": 66,
        "image": "/ampre.webp"
    },
    {
        "group": 664,
        "key": "WA3020",
        "implementation_date": "12 de Agosto al 29 de Noviembre",
        "organization": "Centro de Escritura (Tec CCM y CSF)",
        "population": "Las y los estudiantes de CCM y CSF, atenderán a las y los niños de Tlacoapa",
        "title": "Clases de lectoescritura para niñ@s en Tlacoapa, Xochimilco",
        "objective": "Desarrollar y fortalecer las competencias lectoescritoras de las niñas y niños de la comunidad de Tlacoapa en Xochimilco.",
        "description": "1. Capacitarse con el equipo de docentes del Tec que lideran en proyecto\n2. Planear las sesiones con base en los materiales y actividades que ya existen\n3. Impartir las sesiones con las niñas y los niños en la comunidad\n4. Elaborar reportes de las sesiones y tener sesiones para informar al equipo docente sobre el avance del proyecto",
        "schedule": "Sábados de 09 a 11 hrs",
        "tags": "Todas",
        "abilities": "1. Manejo de grupos\n2. Gusto y facilidad para trabajar con infancias\n3. Creatividad e innovación\n4. Comprensión lectora \n5. Habilidades de escritura\n6. Conocimientos básicos de ortografía y gramática\n7. Gusto por enseñar\n8. Habilidades lúdicas\n9. Organización y manejo de tiempo\n10. Adaptación al espacio y contexto",
        "max": 10,
        "model": "PSP | Proyecto Solidario Presencial",
        "location": "Sede comunitaria de Tlacoapa, Xochimilco. Se contará con apoyo de padres y madres de familia de la comunidad para el manejo, apertura y cierre de la sede. Pista Olímpica Virgilio Uribe, Canal de Cuemanco, Xochimilco, 16040 Ciudad de México, CDMX",
        "duration": "15 semanas",
        "hours": "Hasta 180",
        "extra_comments": "Si bien el Centro de Escritura se propone como OSF, Mónica Lloret, Álvaro Álvarez y Claudia Wittig estarán fungiendo como representantes y contacto del proyecto solidario. Todavía se debe revisar con la comunidad si hay algún día feriado o puente que pueda cancelar algunas sesiones en sábados. Las y los prestadores de servicio social deben llegar por su cuenta, pero se contará con apoyo de miembros de la comunidad para que acompañen a las y los prestadores de servicio social cuando estén en comunidad. Las sesiones con las y los niños comienzan a las 9 y terminan las 11. Deben considerar unos minutos extra para llegar a preparar y para cerrar las instalaciones.",
        "id": 67,
        "image": "/tec-logo.webp"
    }
]

export default projects;
